// Practice passages. Each is a single paragraph between 1200 and 1500 characters.
// `id` is stable so history can reference which passage was typed.

export const PASSAGES = [
  {
    id: "internet-age",
    title: "The Internet Age",
    text: "The internet has transformed the way people live, work, and communicate with one another across the entire world. Only a few decades ago, sending a message to another country could take several days or even weeks, but today a person can share ideas, images, and documents in a matter of seconds. This remarkable change has created countless opportunities for education, business, and personal growth, allowing ordinary individuals to reach a global audience without ever leaving their homes. Students can attend lectures delivered by teachers who live thousands of miles away, while small companies can sell their products to customers in distant markets they could never have imagined reaching before. However, this powerful technology also brings new challenges that society must learn to manage with great care. The rapid spread of false information, the slow erosion of privacy, and the constant pressure to remain connected can quietly affect both our health and our relationships. To use the internet wisely, we must think critically about the content we read and share, protect our personal data from strangers, and remember that real life continues far beyond the glowing screen in front of us. Balance is the key to enjoying the benefits of the digital age while avoiding its many hidden dangers.",
  },
  {
    id: "power-of-habit",
    title: "The Power of Habit",
    text: "Every person is shaped, in large part, by the small habits they repeat each and every day without giving them much thought. The way we wake up in the morning, the food we choose to eat, the manner in which we speak to others, and the tasks we complete before resting at night all form a quiet pattern that slowly defines who we become over time. Good habits, such as reading regularly, exercising, and planning the day ahead, build a strong foundation for a healthy and productive life. Bad habits, on the other hand, can develop just as easily and often without our notice, gradually pulling us away from the goals we truly wish to achieve. The most encouraging truth about habits is that they can be changed with patience and steady effort. By replacing a single harmful routine with a positive one and repeating it until it feels natural, a person can reshape their entire future one small step at a time. Progress may feel slow at first, and the temptation to give up is always present, yet those who continue steadily will eventually look back and be amazed at how far a series of tiny, consistent actions has carried them. In the end, we do not rise to the level of our dreams; instead, we quietly fall to the level of the daily systems and honest habits we have built for ourselves.",
  },
  {
    id: "wonders-of-nature",
    title: "The Wonders of Nature",
    text: "Nature has always been a source of wonder, comfort, and quiet inspiration for people all around the world. From the towering mountains covered in snow to the gentle rivers that wind slowly through green valleys, the natural world offers endless beauty for those who take the time to observe it closely. Forests provide clean air and shelter for countless creatures, while vast oceans hold mysteries that scientists are still working hard to understand. Every season brings its own special charm, whether it is the fresh blossoms of spring, the warm sunshine of summer, the golden leaves of autumn, or the peaceful silence of a winter morning. Spending time outdoors can calm a restless mind, lift a heavy mood, and remind us that we are only a small part of a much larger and more wonderful system. Sadly, human activity has placed great pressure on this delicate balance, and many plants and animals now face a serious threat of disappearing forever. It is our shared responsibility to protect the environment by reducing waste, planting trees, and treating every living thing with respect and genuine care. When we choose to look after nature, we are also looking after ourselves and the many generations who will come after us and depend on the same land, water, and clean air that we so often take for granted today.",
  },
  {
    id: "value-of-time",
    title: "The Value of Time",
    text: "Time is perhaps the most valuable resource that any human being can ever possess, yet it is also the one we tend to waste most freely. Unlike money, which can be earned, lost, and earned again, time moves in only one direction and can never be recovered once it has passed. Every single moment that slips away is gone forever, which is why learning to manage time well is one of the most important skills a person can develop in their entire life. Those who understand the true worth of time plan their days with care, focus on the tasks that matter most, and avoid the endless distractions that constantly compete for their attention. They know that success rarely comes from a single dramatic effort but rather from the steady and wise use of many ordinary hours. On the other hand, people who ignore the value of time often find themselves rushing at the last minute, feeling stressed, and wondering where all their days have gone. It is worth remembering that even the busiest and most accomplished individuals are given exactly the same twenty-four hours in a day as everyone else. The real difference between them lies not in how much time they have, but in how thoughtfully and honestly they choose to spend it on the things they truly believe are worthwhile.",
  },
  {
    id: "importance-of-reading",
    title: "The Importance of Reading",
    text: "Reading is one of the finest habits a person can build, for it opens doors to knowledge, imagination, and understanding that no other activity can quite match. When we read a good book, we are able to travel to distant lands, live through great events of history, and enter the minds of people who lived long before we were even born. Through the simple act of turning a page, we gain access to the wisdom of countless authors who spent years gathering their thoughts and experiences for our benefit. Reading also strengthens the mind in ways that are easy to overlook, improving our vocabulary, sharpening our focus, and teaching us to think clearly about complicated ideas. Children who develop a love of reading early in life often perform better in school and grow into curious, thoughtful adults who never stop learning. In a world that is increasingly filled with quick videos and short messages, sitting quietly with a book has become a rare and precious form of rest for the busy mind. It requires patience and attention, but the rewards are lasting and deep. Whether we choose stories that entertain us, books that teach us new skills, or writings that challenge our beliefs, every page we read adds something valuable to who we are and gently expands the borders of the small world we each live in.",
  },
  {
    id: "spirit-of-teamwork",
    title: "The Spirit of Teamwork",
    text: "Teamwork is the quiet force behind almost every great achievement in the long history of humankind. Very few worthwhile goals can be reached by a single person working entirely alone, for even the most talented individual has limits to their strength, knowledge, and time. When people join together and combine their different skills, they are able to accomplish things that would otherwise seem completely impossible. A successful team is built on trust, clear communication, and a genuine respect for the unique contributions that each member brings to the table. Every person has their own strengths and weaknesses, and a wise group learns to place its members where they can do the most good while supporting one another in the areas where help is needed. Disagreements will naturally arise from time to time, but a strong team treats these moments as chances to find better solutions rather than reasons to divide. Good leaders understand that their role is not simply to give orders but to encourage, to listen carefully, and to help everyone feel valued and heard. When each member sets aside personal pride for the good of the whole, the group becomes far greater than the simple sum of its parts. From building bridges to exploring space, nearly every proud human accomplishment stands as a lasting reminder of what ordinary people can achieve when they choose to work together with a common purpose.",
  },
  {
    id: "journey-of-learning",
    title: "The Journey of Learning",
    text: "Learning is a journey that never truly ends, no matter how old we grow or how much we believe we already know. From the moment we are born, we begin to observe the world around us, asking questions and slowly gathering the knowledge we need to make sense of our surroundings. School gives us an important foundation, teaching us to read, to write, and to reason, but real education continues long after the final classroom door has closed behind us. Every conversation, every mistake, and every new experience carries a lesson for those who are humble enough to notice it. The people who remain curious throughout their lives tend to be the happiest and the most adaptable, because they see change not as a threat but as an exciting opportunity to grow. In a world that is shifting faster than ever before, the ability to keep learning has become one of the most valuable qualities a person can hold. It is important to remember that learning is not only about collecting facts but also about developing wisdom, kindness, and good judgement. A truly educated person knows how to think carefully, treat others with respect, and use their knowledge to make the world a little better than they found it. When we approach each new day with an open and eager mind, life itself becomes our greatest and most generous teacher.",
  },
  {
    id: "kindness-matters",
    title: "Why Kindness Matters",
    text: "Kindness is a simple quality, yet its effect on the world around us is far greater than most people ever realise. A warm smile, a patient word, or a small act of help offered at the right moment can completely change the course of another person's day. We often have no idea what silent struggles the people around us may be carrying, which is exactly why choosing to be gentle and considerate is always worthwhile. Kindness costs us almost nothing, and yet it has the remarkable power to heal wounds, build bridges between strangers, and restore hope where it had begun to fade. What makes it even more wonderful is the way it spreads from one heart to another. When someone is treated with genuine care, they are far more likely to pass that same care along to the next person they meet, creating a quiet chain of goodwill that can travel much further than we will ever see. In our busy and often stressful lives, it is easy to become so focused on our own worries that we forget the needs of those beside us. Yet the smallest gestures, such as listening closely, offering honest encouragement, or simply being present for a friend in need, can leave a mark that lasts for years. A world that chooses kindness, even in its most difficult moments, is a stronger, safer, and far happier place for every single one of us to live in.",
  },
];

export default PASSAGES;
